//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.PostReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://business.dedurando.com.br")]
    public partial class BusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
     
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cityField;
        
        private string confirmation_tokenField;
        
        private string countryField;
        
        private System.Nullable<System.DateTime> created_atField;
        
        private string firstNameField;
        
        private string ipAddressField;
        
        private string lastNameField;
        
        private string mailField;
        
        private string passwordField;
        
        private string phoneField;
        
        private byte[] photoField;
        
        private string resetPasswordTokenField;
        
        private int statusField;
        
        private System.Nullable<long> userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string confirmation_token {
            get {
                return this.confirmation_tokenField;
            }
            set {
                this.confirmation_tokenField = value;
                this.RaisePropertyChanged("confirmation_token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> created_at {
            get {
                return this.created_atField;
            }
            set {
                this.created_atField = value;
                this.RaisePropertyChanged("created_at");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("ipAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
                this.RaisePropertyChanged("mail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=10)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string resetPasswordToken {
            get {
                return this.resetPasswordTokenField;
            }
            set {
                this.resetPasswordTokenField = value;
                this.RaisePropertyChanged("resetPasswordToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<long> userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
     
    public partial class Place : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string cityField;
        
        private string complementField;
        
        private string countryField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string nameField;
        
        private string neighborhoodField;
        
        private long numberField;
        
        private long placeIdField;
        
        private string stateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string complement {
            get {
                return this.complementField;
            }
            set {
                this.complementField = value;
                this.RaisePropertyChanged("complement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string neighborhood {
            get {
                return this.neighborhoodField;
            }
            set {
                this.neighborhoodField = value;
                this.RaisePropertyChanged("neighborhood");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long placeId {
            get {
                return this.placeIdField;
            }
            set {
                this.placeIdField = value;
                this.RaisePropertyChanged("placeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    // 
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> categoryIdField;
        
        private string nameField;
        
        private int statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<long> categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("categoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
     
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Category categoryField;
        
        private string descriptionField;
        
        private System.Nullable<long> itemIdField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Category category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<long> itemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("itemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    // 
    public partial class Post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> createdAtField;
        
        private Item itemField;
        
        private string legendField;
        
        private byte[] photoField;
        
        private Place placeField;
        
        private System.Nullable<long> postIdField;
        
        private int statusField;
        
        private User userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> createdAt {
            get {
                return this.createdAtField;
            }
            set {
                this.createdAtField = value;
                this.RaisePropertyChanged("createdAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Item item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string legend {
            get {
                return this.legendField;
            }
            set {
                this.legendField = value;
                this.RaisePropertyChanged("legend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=3)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
                this.RaisePropertyChanged("photo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public Place place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
                this.RaisePropertyChanged("place");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<long> postId {
            get {
                return this.postIdField;
            }
            set {
                this.postIdField = value;
                this.RaisePropertyChanged("postId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public User user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.dedurando.com.br", ConfigurationName="PostReference.PostService")]
    public interface PostService {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findReturn")]
        Core.PostReference.Post find(Core.PostReference.Post post);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Core.PostReference.BusinessException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="saveReturn")]
        Core.PostReference.Post save(Core.PostReference.Post post);
        
        // CODEGEN: Parameter 'findAllReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAllReturn")]
        Core.PostReference.findAllResponse findAll(Core.PostReference.findAllRequest request);
        
        // CODEGEN: Parameter 'findAllByLegendReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAllByLegendReturn")]
        Core.PostReference.findAllByLegendResponse findAllByLegend(Core.PostReference.findAllByLegendRequest request);
        
        // CODEGEN: Parameter 'findAllByCategoryReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAllByCategoryReturn")]
        Core.PostReference.findAllByCategoryResponse findAllByCategory(Core.PostReference.findAllByCategoryRequest request);
        
        // CODEGEN: Parameter 'findRecentReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findRecentReturn")]
        Core.PostReference.findRecentResponse findRecent(Core.PostReference.findRecentRequest request);
        
        // CODEGEN: Parameter 'findAllByLatitudeAndLongitudeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="findAllByLatitudeAndLongitudeReturn")]
        Core.PostReference.findAllByLatitudeAndLongitudeResponse findAllByLatitudeAndLongitude(Core.PostReference.findAllByLatitudeAndLongitudeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllRequest {
        
        public findAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("findAllReturn")]
        public Post[] findAllReturn;
        
        public findAllResponse() {
        }
        
        public findAllResponse(Post[] findAllReturn) {
            this.findAllReturn = findAllReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByLegend", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByLegendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        public Core.PostReference.Post post;
        
        public findAllByLegendRequest() {
        }
        
        public findAllByLegendRequest(Core.PostReference.Post post) {
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByLegendResponse", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByLegendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("findAllByLegendReturn")]
        public Post[] findAllByLegendReturn;
        
        public findAllByLegendResponse() {
        }
        
        public findAllByLegendResponse(Post[] findAllByLegendReturn) {
            this.findAllByLegendReturn = findAllByLegendReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByCategory", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        public Core.PostReference.Category category;
        
        public findAllByCategoryRequest() {
        }
        
        public findAllByCategoryRequest(Core.PostReference.Category category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByCategoryResponse", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("findAllByCategoryReturn")]
        public Post[] findAllByCategoryReturn;
        
        public findAllByCategoryResponse() {
        }
        
        public findAllByCategoryResponse(Post[] findAllByCategoryReturn) {
            this.findAllByCategoryReturn = findAllByCategoryReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRecent", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findRecentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        public Core.PostReference.Post post;
        
        public findRecentRequest() {
        }
        
        public findRecentRequest(Core.PostReference.Post post) {
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRecentResponse", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findRecentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("findRecentReturn")]
        public Post[] findRecentReturn;
        
        public findRecentResponse() {
        }
        
        public findRecentResponse(Post[] findRecentReturn) {
            this.findRecentReturn = findRecentReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByLatitudeAndLongitude", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByLatitudeAndLongitudeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        public Core.PostReference.Post post;
        
        public findAllByLatitudeAndLongitudeRequest() {
        }
        
        public findAllByLatitudeAndLongitudeRequest(Core.PostReference.Post post) {
            this.post = post;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllByLatitudeAndLongitudeResponse", WrapperNamespace="http://service.dedurando.com.br", IsWrapped=true)]
    public partial class findAllByLatitudeAndLongitudeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.dedurando.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("findAllByLatitudeAndLongitudeReturn")]
        public Post[] findAllByLatitudeAndLongitudeReturn;
        
        public findAllByLatitudeAndLongitudeResponse() {
        }
        
        public findAllByLatitudeAndLongitudeResponse(Post[] findAllByLatitudeAndLongitudeReturn) {
            this.findAllByLatitudeAndLongitudeReturn = findAllByLatitudeAndLongitudeReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostServiceChannel : Core.PostReference.PostService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostServiceClient : System.ServiceModel.ClientBase<Core.PostReference.PostService>, Core.PostReference.PostService {
        
        public PostServiceClient() {
        }
        
        public PostServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Core.PostReference.Post find(Core.PostReference.Post post) {
            return base.Channel.find(post);
        }
        
        public Core.PostReference.Post save(Core.PostReference.Post post) {
            return base.Channel.save(post);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.PostReference.findAllResponse Core.PostReference.PostService.findAll(Core.PostReference.findAllRequest request) {
            return base.Channel.findAll(request);
        }
        
        public Post[] findAll() {
            Core.PostReference.findAllRequest inValue = new Core.PostReference.findAllRequest();
            Core.PostReference.findAllResponse retVal = ((Core.PostReference.PostService)(this)).findAll(inValue);
            return retVal.findAllReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.PostReference.findAllByLegendResponse Core.PostReference.PostService.findAllByLegend(Core.PostReference.findAllByLegendRequest request) {
            return base.Channel.findAllByLegend(request);
        }
        
        public Post[] findAllByLegend(Core.PostReference.Post post) {
            Core.PostReference.findAllByLegendRequest inValue = new Core.PostReference.findAllByLegendRequest();
            inValue.post = post;
            Core.PostReference.findAllByLegendResponse retVal = ((Core.PostReference.PostService)(this)).findAllByLegend(inValue);
            return retVal.findAllByLegendReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.PostReference.findAllByCategoryResponse Core.PostReference.PostService.findAllByCategory(Core.PostReference.findAllByCategoryRequest request) {
            return base.Channel.findAllByCategory(request);
        }
        
        public Post[] findAllByCategory(Core.PostReference.Category category) {
            Core.PostReference.findAllByCategoryRequest inValue = new Core.PostReference.findAllByCategoryRequest();
            inValue.category = category;
            Core.PostReference.findAllByCategoryResponse retVal = ((Core.PostReference.PostService)(this)).findAllByCategory(inValue);
            return retVal.findAllByCategoryReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.PostReference.findRecentResponse Core.PostReference.PostService.findRecent(Core.PostReference.findRecentRequest request) {
            return base.Channel.findRecent(request);
        }
        
        public Post[] findRecent(Core.PostReference.Post post) {
            Core.PostReference.findRecentRequest inValue = new Core.PostReference.findRecentRequest();
            inValue.post = post;
            Core.PostReference.findRecentResponse retVal = ((Core.PostReference.PostService)(this)).findRecent(inValue);
            return retVal.findRecentReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Core.PostReference.findAllByLatitudeAndLongitudeResponse Core.PostReference.PostService.findAllByLatitudeAndLongitude(Core.PostReference.findAllByLatitudeAndLongitudeRequest request) {
            return base.Channel.findAllByLatitudeAndLongitude(request);
        }
        
        public Post[] findAllByLatitudeAndLongitude(Core.PostReference.Post post) {
            Core.PostReference.findAllByLatitudeAndLongitudeRequest inValue = new Core.PostReference.findAllByLatitudeAndLongitudeRequest();
            inValue.post = post;
            Core.PostReference.findAllByLatitudeAndLongitudeResponse retVal = ((Core.PostReference.PostService)(this)).findAllByLatitudeAndLongitude(inValue);
            return retVal.findAllByLatitudeAndLongitudeReturn;
        }
    }
}
